### ISSUE TITLE
这不是官方推荐demo吗？通知栏都没显示也没人解决的啊

### ISSUE THREAD

**Issue by LFMyGitHub** [amap-demo/android-o-backgroundlocation#2]

**Comment by pdliuw** [comment]
经过本人验证：通知栏不显示事情属实

测试机型：
* 系统：Android10
* 品牌：OPPO Ace2

**Comment by pdliuw** [comment]
> 经过本人验证：通知栏不显示事情属实
> 
> 测试机型：
> 
> * 系统：Android10
> * 品牌：OPPO Ace2

此“高德地图官方Demo问题非常多”.....

**Comment by pdliuw** [comment]
> > 经过本人验证：通知栏不显示事情属实
> > 测试机型：
> > 
> > * 系统：Android10
> > * 品牌：OPPO Ace2
> 
> 此“高德地图官方Demo问题非常多”.....

使用此Demo运行在 “上述机型” 会导致“定位失败 频发”，在“更新到最新SDK后，一次即可成功定位”.....

**Comment by 5vwhm** [comment]
通知栏已修复，定位SDK已更新到最新版本。
@pdliuw 感谢反馈，欢迎验证。

**Comment by 5vwhm** [comment]
> > > 经过本人验证：通知栏不显示事情属实
> > > 测试机型：
> > > 
> > > * 系统：Android10
> > > * 品牌：OPPO Ace2
> > 
> > 
> > 此“高德地图官方Demo问题非常多”.....
> 
> 使用此Demo运行在 “上述机型” 会导致“定位失败 频发”，在“更新到最新SDK后，一次即可成功定位”.....



> 经过本人验证：通知栏不显示事情属实
> 
> 测试机型：
> 
> * 系统：Android10
> * 品牌：OPPO Ace2
通知栏已修复，定位SDK已更新到最新版本。感谢反馈。

**Comment by shixiaoquan** [comment]
> 通知栏已修复，定位SDK已更新到最新版本。
> @pdliuw 感谢反馈，欢迎验证。

没修复啊，还是弹不出来， MI 9 MIUI12

**Comment by shixiaoquan** [comment]
> > 通知栏已修复，定位SDK已更新到最新版本。
> > @pdliuw 感谢反馈，欢迎验证。
> 
> 没修复啊，还是弹不出来， MI 9 MIUI12

OPPO R17 Pro ColorOS v7.1
